config/routes.rb
Rails.application.routes.draw do
  resources :events do
    get :get_events, on: :collection
  end
  

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  respond_to :json
  
  def show_events
    events = []
    @events.each do |event|
      events << {
        :id => event.id, 
        :title => event.project, 
        #:description => "#{event.description}",
        #:responsible_person => "#{event.responsible_person}", 
        #:gov_type => "#{event.gov_type}",
        #:due_date => "#{event.due_date}", 
        #:completed_date => "#{event.completed_date}",
        :start => event.start_time, 
        :end => event.end_time
      }
      end
      render json: events.to_json
  end
  
  # GET /events
  # GET /events.json
  def index
    if(params.has_key?(:classes))
		@events = Event.where(gov_type: params[:classes])	
   else
		@events = Event.all
	end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:project, :description, :responsible_person, :gov_type, :due_date, :completed_date, :start_time, :end_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project %><br>
    <%= f.text_field :project %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :responsible_person %><br>
    <%= f.text_field :responsible_person %>	
  </div>    
  <div class="field">
    <%= f.label :gov_type %><br>
    <%= select("event", "gov_type", options_for_select(["Federal", "State", "Internal UNM"]) ) %>
  </div>
  
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.datetime_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :completed_date %><br>
    <%= f.datetime_select :completed_date %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>OIA Calendar</h1>
<script>
function isChecked()
{
var source = "/events.json?";
ids = ["Federal","State","Internal UNM"]
for (i = 0; i < ids.length; i++) {
if (document.getElementById(ids[i]).checked)
{
source += "classes[]="+document.getElementById(ids[i]).value+"&"
}
 }
document.getElementById("calendar").innerText = "";

$('#calendar').fullCalendar({
eventSources: [source]
   })


}
</script>

<div id="filter">
Filter by Report Type:	
<input type="checkbox" id="Federal" value="Federal"  onclick="isChecked(this);">Federal&nbsp;&nbsp;&nbsp;&nbsp;
<input type="checkbox" id="State" value="State"  onclick="isChecked(this);">State&nbsp;&nbsp;&nbsp;&nbsp;
<input type="checkbox" id="Internal UNM" value="Internal UNM"  onclick="isChecked(this);">Internal UNM&nbsp;&nbsp;&nbsp;&nbsp;
</div>


<br>

<%= link_to 'New Event', new_event_path %>

<div id='calendar'>
</div>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @event.project %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Responsible person:</strong>
  <%= @event.responsible_person %>
</p>

<p>
  <strong>Gov type:</strong>
  <%= @event.gov_type %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @event.due_date %>
</p>

<p>
  <strong>Completed date:</strong>
  <%= @event.completed_date %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %> |
<%= link_to "delete", @event, :method=>:delete, :class=>:destroy %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<link rel='stylesheet' href='fullcalendar/fullcalendar.css' />
<script src='lib/jquery.min.js'></script>
<script src='lib/moment.min.js'></script>
<script src='fullcalendar/fullcalendar.js'></script>  
<title>Oiacalendar</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>
<body>
<script src='//cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/fullcalendar.min.js'></script>
<link rel="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/fullcalendar.css">
<%= yield %>
<script>


	$(document).ready(function() {

	    // page is now ready, initialize the calendar...
		var curSource = new Array();

		$.getJSON("/events.json", function(json){
		    curSource = json;
		});
		
				
		
	    $('#calendar').fullCalendar({
			eventSources: ['/events.json']
	        // put your options and callbacks here
			// events: '/events.json'
	    })

	});
</script>

</body>
</html>